baseURL = 'https://joshuak.im/'
languageCode = 'en-us'
title = 'Joshua Kim'

theme = 'stack'

[[widgets.homepage]]
type = "search"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = 'G-HCZX138JLT'