mainSections = [ "movies", "blog" ]
featuredImageField = "image"
rssFullContent = true

[footer]
since = 2_025

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
math = false
toc = true
readingTime = true

#[article.license]
#enabled = true
#default = "Licensed under CC BY-NC-SA 4.0"